import fetch from 'node-fetch'
let handler = async (m, { conn, command }) => {
if (!db.data.chats[m.chat].modohorny && m.isGroup) throw '*[ ⚠️ ] Los comandos +18 estan desactivados en este grupo, si es administrador de este grupo y desea activarlos escriba #enable nsfw*'
let url = packmen[Math.floor(Math.random() * packmen.length)]
conn.sendButton(m.chat, `_🥵 Pack 3 🥵_`, author, url, [['◀️𝚂𝙸𝙶𝚄𝙸𝙴𝙽𝚃𝙴▶️', `/${command}`]], m)
}
handler.help = ['pack3']
handler.tags = ['internet']
handler.command = /^(pack3)$/i
export default handler

global.packmen = [
  "https://imgur.com/iHc6sZ4.jpg",
"https://imgur.com/Q8Mmxw6.jpg",
"https://imgur.com/7mFDe4K.jpg",
"https://imgur.com/DRl91d8.jpg",
"https://imgur.com/7XM0WkE.jpg",
"https://imgur.com/ABSZBYs.jpg",
"https://imgur.com/tS4sgw1.jpg",
"https://imgur.com/dQu7k8k.jpg",
"https://imgur.com/QVeMm0s.jpg",
"https://imgur.com/lJfW0d2.jpg",
"https://imgur.com/ChmCKMV.jpg",
"https://imgur.com/s5r9BGS.jpg",
"https://imgur.com/PUzgeUI.jpg",
"https://imgur.com/c4WBAw9.jpg",
"https://imgur.com/QPjDq0z.jpg",
"https://imgur.com/KNtxayz.jpg",
"https://imgur.com/uf1jIxP.jpg",
"https://imgur.com/aixogRT.jpg",
"https://imgur.com/Ds1NVNt.jpg",
"https://imgur.com/yfDjEzr.jpg",
"https://imgur.com/Ndn91w4.jpg",
"https://imgur.com/e0M43I1.jpg",
"https://imgur.com/v1wHsgZ.jpg",
"https://imgur.com/HQkOapL.jpg",
"https://imgur.com/kNRXFMJ.jpg",
"https://imgur.com/jF10gpV.jpg",
"https://imgur.com/V1Rh6eb.jpg",
"https://imgur.com/nXmPFsd.jpg",
"https://imgur.com/TuLGggY.jpg",
"https://imgur.com/WQ3aQtZ.jpg",
"https://imgur.com/Cc3AJ1C.jpg",
"https://imgur.com/gMSN9vI.jpg",
  "https://i.imgur.com/mwLJaxU.jpg",
  "https://i.imgur.com/9ptmlPl.jpg",
  "https://imgur.com/wjvjj0J.jpg",
  "https://imgur.com/7VMDI3q.jpg",
  "https://imgur.com/MjJGoNj.jpg",
  "https://imgur.com/54xLIpP.jpg",
  "https://imgur.com/HJXM9Tw.jpg",
  "https://imgur.com/KJ2IrtN.jpg",
  "https://imgur.com/IIgCKuN.jpg",
  "https://imgur.com/8fAeR4e.jpg",
  "https://imgur.com/exCEAt7.jpg",
  "https://imgur.com/zBc3p3C.jpg",
  "https://imgur.com/Av6Rigg.jpg",
  "https://imgur.com/vli8uZP.jpg",
  "https://imgur.com/Femgp8h.jpg",
  "https://imgur.com/8bnKfOi.jpg",
  "https://i.imgur.com/38tVliz.jpg",
  "https://i.imgur.com/2NqCKE3.jpg",
  "https://i.imgur.com/pveviMG.jpg",
  "https://imgur.com/FmSmrge.jpg",
  "https://imgur.com/JkErFFm.jpg",
  "https://imgur.com/FH0tv41.jpg",
  "https://i.imgur.com/d71dnkv.jpg",
  "https://i.imgur.com/cr7Ypj1.jpg",
  "https://i.imgur.com/jAxzCj4.jpg",
  "https://i.imgur.com/xokuFLf.jpg",
  "https://imgur.com/2GvlGmP.jpg",
  "https://imgur.com/ApFzKX7.jpg",
  "https://imgur.com/mcI4nSu.jpg",
  "https://imgur.com/A0t8hKv.jpg",
  "https://imgur.com/uqlHzq3.jpg",
  "https://i.imgur.com/Hi4zLaf.jpg",
  "https://i.imgur.com/OlaQtwW.jpg",
  "https://i.imgur.com/Dm4GLuF.jpg",
  "https://i.imgur.com/k6Y2E9b.jpg",
  "https://i.imgur.com/1rk7jdu.jpg",
  "https://i.imgur.com/TFmEVPc.jpg",
  "https://i.imgur.com/0XefLlJ.jpg",
  "https://i.imgur.com/bwa9LYZ.jpg",
  "https://i.imgur.com/WgrpTmg.jpg",
  "https://i.imgur.com/Z5f5YAw.jpg",
  "https://i.imgur.com/xEuBtPO.jpg",
  "https://i.imgur.com/NA0fHxn.jpg",
  "https://i.imgur.com/InueCKQ.jpg",
  "https://i.imgur.com/3syOcHe.jpg",
  "https://i.imgur.com/N1dgels.jpg",
  "https://i.imgur.com/IxKAJaV.jpg",
  "https://i.imgur.com/8VrxL1d.jpg",
  "https://i.imgur.com/8B4Y0bG.jpg",
  "https://i.imgur.com/wgkGOjF.jpg",
  "https://i.imgur.com/765Wi6q.jpg",
  "https://i.imgur.com/5joeWnm.jpg",
  "https://i.imgur.com/71fjmmM.jpg",
  "https://i.imgur.com/cAuKeyZ.jpg",
  "https://i.imgur.com/SDZ2Hs5.jpg",
  "https://i.imgur.com/skkEyqI.jpg",
  "https://i.imgur.com/6dXFsBW.jpg",
  "https://imgur.com/2GvlGmP.jpg",
  "https://imgur.com/ApFzKX7.jpg",
  "https://imgur.com/mcI4nSu.jpg",
  "https://imgur.com/A0t8hKv.jpg",
  "https://imgur.com/uqlHzq3.jpg",
  "https://i.imgur.com/6CeG9ZX.jpg"
]
